package com.example.hapticbeat

object Constants {
    const val ACTION_START_SERVICE = "ACTION_START_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_SET_GLOBAL_INTENSITY = "ACTION_SET_GLOBAL_INTENSITY"
    const val ACTION_SET_MODE = "ACTION_SET_MODE"
    const val ACTION_SET_HAPTIC_TYPE = "ACTION_SET_HAPTIC_TYPE"
    const val ACTION_SET_MIC_INPUT = "ACTION_SET_MIC_INPUT"
    const val ACTION_SET_FFT_ENABLED = "ACTION_SET_FFT_ENABLED"
    const val ACTION_REQUEST_SERVICE_STATUS = "ACTION_REQUEST_SERVICE_STATUS"
    const val ACTION_SERVICE_STATUS_UPDATE = "ACTION_SERVICE_STATUS_UPDATE"

    // New action for MediaProjection result
    const val ACTION_MEDIA_PROJECTION_RESULT = "ACTION_MEDIA_PROJECTION_RESULT"

    const val EXTRA_MEDIA_PROJECTION_RESULT_CODE = "EXTRA_MEDIA_PROJECTION_RESULT_CODE"
    const val EXTRA_MEDIA_PROJECTION_RESULT_DATA = "EXTRA_MEDIA_PROJECTION_RESULT_DATA"
    const val EXTRA_GLOBAL_INTENSITY = "EXTRA_GLOBAL_INTENSITY"
    const val EXTRA_HAPTIC_MODE = "EXTRA_HAPTIC_MODE"
    const val EXTRA_HAPTIC_TYPE = "EXTRA_HAPTIC_TYPE" // Added missing constant
    const val EXTRA_IS_MIC_INPUT_ENABLED = "EXTRA_IS_MIC_INPUT_ENABLED"
    const val EXTRA_IS_RUNNING = "EXTRA_IS_RUNNING"
    const val EXTRA_GLOBAL_INTENSITY_PERCENT = "EXTRA_GLOBAL_INTENSITY_PERCENT"
    const val EXTRA_FFT_ENABLED = "EXTRA_FFT_ENABLED"
    const val EXTRA_CURRENT_HAPTIC_MODE = "EXTRA_CURRENT_HAPTIC_MODE" // Added missing constant
    const val EXTRA_CURRENT_HAPTIC_TYPE = "EXTRA_CURRENT_HAPTIC_TYPE" // Added missing constant
}
